In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder  ##Usando condificação de Etiqueta

In [2]:
train = pd.read_csv('train_values.csv')
train_pred = pd.read_csv('train_labels.csv')
test = pd.read_csv('test_values.csv')

In [3]:
train.describe()

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
count,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,1.550000,131.311111,3.155556,0.694444,0.161111,1.050000,249.211111,1.010000,0.688889,54.811111,149.483333,0.316667
std,0.618838,17.010443,0.938454,0.969347,0.368659,0.998742,52.717969,1.121357,0.464239,9.334737,22.063513,0.466474
min,1.000000,94.000000,1.000000,0.000000,0.000000,0.000000,126.000000,0.000000,0.000000,29.000000,96.000000,0.000000
25%,1.000000,120.000000,3.000000,0.000000,0.000000,0.000000,213.750000,0.000000,0.000000,48.000000,132.000000,0.000000
50%,1.000000,130.000000,3.000000,0.000000,0.000000,2.000000,245.500000,0.800000,1.000000,55.000000,152.000000,0.000000
75%,2.000000,140.000000,4.000000,1.000000,0.000000,2.000000,281.250000,1.600000,1.000000,62.000000,166.250000,1.000000
max,3.000000,180.000000,4.000000,3.000000,1.000000,2.000000,564.000000,6.200000,1.000000,77.000000,202.000000,1.000000

In [4]:
train.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,0z64un,1,normal,128,2,0,0,2,308,0.0,1,45,170,0
1,ryoo3j,2,normal,110,3,0,0,0,214,1.6,0,54,158,0
2,yt1s1x,1,normal,125,4,3,0,2,304,0.0,1,77,162,1
3,l2xjde,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0
4,oyt4ek,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0

In [5]:
test.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,olalu7,2,reversible_defect,170,1,0,0,2,288,0.2,1,59,159,0
1,z9n6mx,1,normal,138,4,0,0,0,183,1.4,0,35,182,0
2,5k4413,2,reversible_defect,120,4,0,0,2,177,2.5,1,43,120,1
3,mrg7q5,1,normal,102,3,1,0,0,318,0.0,0,60,160,0
4,uki4do,2,normal,138,4,1,0,2,166,3.6,1,61,125,1

In [6]:
train.shape

(180, 14)

In [7]:
train.isnull().sum().sort_values(ascending=False).head()

exercise_induced_angina     0
max_heart_rate_achieved     0
age                         0
sex                         0
oldpeak_eq_st_depression    0
dtype: int64

In [8]:
test.isnull().sum().sort_values(ascending=False).head()

exercise_induced_angina     0
max_heart_rate_achieved     0
age                         0
sex                         0
oldpeak_eq_st_depression    0
dtype: int64

In [9]:
train.dtypes

patient_id                               object
slope_of_peak_exercise_st_segment         int64
thal                                     object
resting_blood_pressure                    int64
chest_pain_type                           int64
num_major_vessels                         int64
fasting_blood_sugar_gt_120_mg_per_dl      int64
resting_ekg_results                       int64
serum_cholesterol_mg_per_dl               int64
oldpeak_eq_st_depression                float64
sex                                       int64
age                                       int64
max_heart_rate_achieved                   int64
exercise_induced_angina                   int64
dtype: object

In [10]:
lab_Enc = LabelEncoder()
train['thal'] = lab_Enc.fit_transform(train['thal'])
train.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,0z64un,1,1,128,2,0,0,2,308,0.0,1,45,170,0
1,ryoo3j,2,1,110,3,0,0,0,214,1.6,0,54,158,0
2,yt1s1x,1,1,125,4,3,0,2,304,0.0,1,77,162,1
3,l2xjde,1,2,152,4,0,0,0,223,0.0,1,40,181,0
4,oyt4ek,3,2,178,1,0,0,2,270,4.2,1,59,145,0

In [11]:
test.dtypes

patient_id                               object
slope_of_peak_exercise_st_segment         int64
thal                                     object
resting_blood_pressure                    int64
chest_pain_type                           int64
num_major_vessels                         int64
fasting_blood_sugar_gt_120_mg_per_dl      int64
resting_ekg_results                       int64
serum_cholesterol_mg_per_dl               int64
oldpeak_eq_st_depression                float64
sex                                       int64
age                                       int64
max_heart_rate_achieved                   int64
exercise_induced_angina                   int64
dtype: object

In [12]:
test['thal'] = lab_Enc.fit_transform(test['thal'])
test.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,olalu7,2,2,170,1,0,0,2,288,0.2,1,59,159,0
1,z9n6mx,1,1,138,4,0,0,0,183,1.4,0,35,182,0
2,5k4413,2,2,120,4,0,0,2,177,2.5,1,43,120,1
3,mrg7q5,1,1,102,3,1,0,0,318,0.0,0,60,160,0
4,uki4do,2,1,138,4,1,0,2,166,3.6,1,61,125,1

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [14]:
X = train.drop(['patient_id'],axis=1)
y = train_pred['heart_disease_present']

In [15]:
modelo = DecisionTreeClassifier(random_state=1)
modelo.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')

In [16]:
params={
    'min_samples_split' : range(10,500,20),
    'max_depth': range(1,20,2)
}
grid = GridSearchCV(modelo,params)
grid.fit(X,y)
modelo = grid.best_estimator_
modelo.fit(X,y)

C:\Users\devin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\devin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')

In [17]:
recursos = train.columns.values

features_importance = zip(modelo.feature_importances_,recursos)
for importancia,recurso in sorted(features_importance, reverse=True):
    print("%s: %f%%" % (recurso, importancia*100))

slope_of_peak_exercise_st_segment: 34.210206%
chest_pain_type: 14.069759%
resting_blood_pressure: 13.178933%
serum_cholesterol_mg_per_dl: 9.718619%
oldpeak_eq_st_depression: 7.655654%
resting_ekg_results: 6.201157%
age: 5.520626%
patient_id: 4.333887%
thal: 2.964141%
fasting_blood_sugar_gt_120_mg_per_dl: 2.147018%
sex: 0.000000%
num_major_vessels: 0.000000%
max_heart_rate_achieved: 0.000000%

In [18]:
modelo.score(X,y)

0.9277777777777778

In [19]:
modelo_val = cross_val_score(modelo,X,y,cv=5)
print(modelo_val.mean())

0.7166666666666667

In [20]:
new_test = test.drop(['patient_id'],axis=1)

In [37]:
predicao = modelo.predict_proba(new_test)
pred = np.array(predicao)
pred[:,0]

array([0.5       , 0.98245614, 0.        , 0.5       , 0.        ,
       0.98245614, 0.77777778, 0.5       , 0.98245614, 0.98245614,
       0.        , 0.        , 0.98245614, 0.        , 0.98245614,
       0.98245614, 0.98245614, 0.98245614, 0.        , 0.98245614,
       0.        , 0.98245614, 0.28571429, 0.77777778, 0.1       ,
       0.        , 0.        , 1.        , 1.        , 0.98245614,
       0.        , 0.        , 0.        , 0.        , 0.77777778,
       0.98245614, 0.77777778, 0.98245614, 1.        , 0.98245614,
       0.        , 0.98245614, 0.        , 0.98245614, 0.        ,
       0.98245614, 0.98245614, 0.25      , 0.98245614, 1.        ,
       0.        , 0.98245614, 0.        , 0.77777778, 1.        ,
       0.98245614, 0.        , 1.        , 0.98245614, 0.98245614,
       0.98245614, 0.        , 0.98245614, 0.        , 0.98245614,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.98245614, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.5       ,
       0.        , 1.        , 0.98245614, 0.        , 0.25      ,
       0.25      , 0.98245614, 0.28571429, 0.98245614, 0.77777778])

# Resolver problema do predict_proba q retorna uma lista de array

In [39]:
submission = pd.DataFrame()
submission['patient_id'] = test['patient_id']
submission['heart_disease_present'] = pred[:,0]
submission.to_csv('submission.csv',index=False)